# TODO:
# * checkers: sanitizers, valgrind ?

name: CI
on:
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install gdb
    - name: Run tests
      run: scripts/travis.sh
  CSA:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install clang-tools
    - name: Run tests
      run: scan-build --keep-going --status-bugs make clean all
  Coverage:
    runs-on: ubuntu-latest
    environment: secrets
    env:
      COVERAGE: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install gdb
    - name: Run tests
      run: scripts/travis.sh
